### ISSUE TITLE
Не хватает $ в правилах regexp 

### ISSUE THREAD

**Issue by Nexword** [EmptyLibra/Configure-Xray-with-VLESS-Reality-on-VPS-server#2]
Сейчас в md файле написано:

> "geosite:category-ru,regexp:.*\.ru,regexp:.*\.su"

Но, если оставить как есть, то, к примеру, static.rutracker.cc будет попадать под правило blocked. Возможно, знак $ в конце является обязательным.
Должно быть:
geosite:category-ru,regexp:.*\.ru$,regexp:.*\.su$

**Comment by EmptyLibra** [comment]
Да, вы правы. Он указывает на конец строки.
Спасибо, исправлю
